[versions]
lombok = "1.18.30"
jetbrains-annotations = "24.1.0"
jreleaser = "1.18.0"
junit = "5.10.1"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }

[bundles]
junit = ["junit-api", "junit-engine", "junit-params"]

[plugins]
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }